# Generated by Django 3.0.3 on 2020-02-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excerpt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('last_date_posted', models.DateTimeField(blank=True)),
                ('date_to_post', models.DateTimeField(blank=True)),
            ],
        ),
    ]
