# Generated by Django 3.0.3 on 2020-02-18 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spiritual_treasures', '0002_excerpt_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excerpt',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='excerpt',
            name='date_to_post',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='excerpt',
            name='last_date_posted',
            field=models.DateTimeField(null=True),
        ),
    ]
